# Generated by Django 4.0.1 on 2022-01-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop Music', 'Pop Music'), ('Bollybood', 'BollyBood'), ('Techno', 'Techno'), ('Hip Hop Music', 'Hip Hop Music'), ('Country', 'Country'), ('Folk', 'Folk'), ('Classical', 'Classical')], max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
