# Generated by Django 4.0.4 on 2022-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0005_alter_album_genre_alter_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Bollybood', 'BollyBood'), ('Techno', 'Techno'), ('Country', 'Country'), ('Folk', 'Folk'), ('Hip Hop Music', 'Hip Hop Music'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('Rock', 'Rock')], max_length=50),
        ),
    ]
