# Generated by Django 4.0.4 on 2022-05-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0006_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Pop Music', 'Pop Music'), ('Bollybood', 'BollyBood'), ('Techno', 'Techno'), ('Country', 'Country'), ('Folk', 'Folk'), ('Hip Hop Music', 'Hip Hop Music'), ('Rock', 'Rock'), ('Classical', 'Classical')], max_length=50),
        ),
    ]
