# Generated by Django 4.0.4 on 2022-05-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0007_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Country', 'Country'), ('Classical', 'Classical'), ('Hip Hop Music', 'Hip Hop Music'), ('Bollybood', 'BollyBood'), ('Folk', 'Folk'), ('Techno', 'Techno'), ('Pop Music', 'Pop Music'), ('Rock', 'Rock')], max_length=50),
        ),
    ]
