# Generated by Django 4.0.4 on 2022-06-08 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Music', '0008_alter_album_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(choices=[('Techno', 'Techno'), ('Bollywood', 'Bollywood'), ('Pop Music', 'Pop Music'), ('Classical', 'Classical'), ('K-POP', 'K-POP'), ('Hip Hop and Rap', 'Hip Hop and Rap'), ('Country', 'Country'), ('Hollywood', 'Hollywood'), ('Hip Hop Music', 'Hip Hop Music'), ('Folk', 'Folk'), ('Rock', 'Rock'), ('Metal', 'Metal')], max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='lang',
            field=models.CharField(choices=[('Kumaoni', 'Kumaoni'), ('Punjabi', 'Punjabi'), ('Hindi', 'Hindi'), ('English', 'English'), ('korean', 'korean')], max_length=200),
        ),
        migrations.CreateModel(
            name='Recent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlistName', models.CharField(max_length=200)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isFav', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
